# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orbit_schema',
            field=models.CharField(blank=True, choices=[('Atomic', 'Electron shell schema'), ('Planetary', 'Solar system schema'), ('Dyson', 'Dyson sphere schema')], max_length=128, null=True),
        ),
    ]
