# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_orbit_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orbit_schema',
            field=models.CharField(blank=True, choices=[('Atomic', 'Electron shell schema')], max_length=128, null=True),
        ),
    ]
