# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170712_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orbit_schema',
            field=models.CharField(choices=[('Atomic', 'Electron shell schema')], default='Atomic', max_length=128),
            preserve_default=False,
        ),
    ]
