# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Doohickey', 'Delightful doohickey'), ('Thingamajig', 'Thrilling thingamajig')], max_length=24)),
                ('description', models.CharField(max_length=2048)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('is_launched', models.BooleanField(default=False)),
                ('launched_on', models.DateTimeField(blank=True)),
                ('solidity_code', models.TextField(max_length=20480)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
