# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robit',
            name='launched_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
