# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20170711_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('robit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.RoBit')),
            ],
        ),
    ]
